поправки
Roksolana0101/goit-team-project-group07 pull request #53
Opened 2022-08-30 18:15 UTC by Olexandr5

ніби все

2022-08-30 19:52 UTC, Roksolana0101 requested changes
треба уточнити перед прийняттям правок

2022-08-30 19:52 UTC, Roksolana0101 commented on src/sass/layout/_customers.scss
>      padding-top: 60px;
а до якого класу тоді ці всі властивості? ти ж видаляєш клас .сustomers__container просто виидаляєш і лиишаєш властивості а до  чого вони тоді застосуються

2022-08-30 19:52 UTC, Roksolana0101 commented on src/sass/layout/_subscribe.scss
>      padding-bottom: 100px;
тут так само ти лишаєш лише амперсант а де клас до якого власне стиилі мають бути застосовані?

2022-08-30 20:04 UTC, Olexandr5 commented on src/sass/layout/_customers.scss
>      padding-top: 60px;
що щось старе я в коді такого не знпходжу

2022-08-30 20:05 UTC, Olexandr5 commented on src/sass/layout/_subscribe.scss
>      padding-bottom: 100px;
і тут не знаходжу просто стерти і все

2022-08-30 20:17 UTC, Olexandr5 commented on src/sass/layout/_subscribe.scss
>      padding-bottom: 100px;
то що мені тут зробити

2022-08-31 04:34 UTC, Olexandr5 reviewed
переглянув

2022-08-31 04:40 UTC, Roksolana0101 approved these changes

2022-08-31 04:44 UTC, merged